name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        java: [17, 21, 25]
    steps:
      - uses: actions/checkout@v4

      - uses: abxst/actions/strict@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          build-args: JAVA_VERSION=${{ matrix.java }}
          tags: |
            type=raw,value=${{ matrix.java }},enable={{is_default_branch}}
            type=raw,value=${{ matrix.java }}-{{sha}}-{{date 'DDMMYYYY'}},enable={{is_default_branch}}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' && matrix.java == 25 }}